/**
 * Theme configuration for sprint-review template
 *
 * Uses shared ThemeProvider from lib/theme and brand settings from brand.ts.
 */

import { ThemeProvider, useTheme, createStyles } from '../../../../lib/theme';
import type { Theme } from '../../../../lib/theme';
import { brand, brandTheme } from './brand';

// Default theme - loaded from brand.ts (generated by /new-video)
export const defaultTheme: Theme = brandTheme;

// Alternative themes (extend the brand theme)
export const darkTheme: Theme = {
  ...defaultTheme,
  colors: {
    ...defaultTheme.colors,
    primary: brand.colors.primary,
    primaryLight: brand.colors.primaryLight,
    textDark: '#f1f5f9',
    textMedium: '#cbd5e1',
    textLight: '#94a3b8',
    bgLight: '#0f172a',
    bgDark: '#020617',
    bgOverlay: 'rgba(15, 23, 42, 0.95)',
    divider: '#334155',
  },
};

// Re-export ThemeProvider and useTheme from lib
export { ThemeProvider, useTheme, createStyles };
export type { Theme };

// Re-export brand for direct access
export { brand, brandTheme } from './brand';
