#!/usr/bin/env python3
"""Export WebVTT captions from a rendered intro video.

Wraps tools/transcribe.py (Modal Whisper, screenplay-aware initial_prompt)
and chunks word-level timestamps into short single-line cues. Output is
text-only, no positioning cue settings — the website's VideoHeroOverlay
draws the caption layer itself with brand-styled CSS.

Usage:
    python3 tools/export_vtt.py <project-name> [--max-chars 28] [--max-cue-sec 2.0]

Inputs:
    projects/<name>/out/intro.mp4
    projects/<name>/SCREENPLAY.md   (used as Whisper initial_prompt hint)

Output:
    projects/<name>/out/intro.vtt
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
TRANSCRIBE_PY = ROOT / "video_toolkit" / "transcribe.py"


@dataclass(frozen=True)
class Word:
    start: float  # seconds
    end: float
    word: str


@dataclass(frozen=True)
class Cue:
    start: float
    end: float
    text: str


SENTENCE_END = {".", "?", "!"}
SOFT_BREAK = {",", ";", ":"}


def chunk_words_into_cues(
    words: Iterable[Word],
    max_chars: int,
    max_cue_sec: float,
) -> list[Cue]:
    """Group word-level timestamps into short single-line VTT cues.

    Rules:
    - Accumulate words until either char budget OR time budget exceeded.
    - Sentence-end punctuation (./?/!) ALWAYS ends the current cue.
    - Soft-break punctuation (,/;/:) is preferred as a cue break point when
      the next word would exceed the budget.
    - One short phrase per cue keeps each caption to a single line (web
      reference format: media.example.com/public/video/
      intro-hero-mockup.en.vtt).
    """
    words = list(words)
    cues: list[Cue] = []
    current: list[Word] = []

    def emit():
        if not current:
            return
        text = " ".join(w.word for w in current).strip()
        cues.append(Cue(start=current[0].start, end=current[-1].end, text=text))
        current.clear()

    for w in words:
        current.append(w)
        text = " ".join(x.word for x in current)
        spans = current[-1].end - current[0].start

        # Hard sentence-end ALWAYS ends cue.
        if any(w.word.endswith(p) for p in SENTENCE_END):
            emit()
            continue

        # Over either budget? Try to back off to a soft break.
        if len(text) >= max_chars or spans >= max_cue_sec:
            # If the most recent word ends with a soft break, end here.
            if any(current[-1].word.endswith(p) for p in SOFT_BREAK):
                emit()
                continue
            # Look back for a soft break within current. If found, split.
            for i in range(len(current) - 2, -1, -1):
                if any(current[i].word.endswith(p) for p in SOFT_BREAK):
                    # Emit up to and including position i; carry the rest.
                    head, tail = current[: i + 1], current[i + 1 :]
                    current.clear()
                    current.extend(head)
                    emit()
                    current.extend(tail)
                    break
            else:
                # No soft break found — hard cut.
                emit()

    emit()
    return cues


def format_timestamp(seconds: float) -> str:
    """Format seconds as WebVTT timestamp: MM:SS.mmm (no hour for sub-1h videos)."""
    if seconds < 0:
        seconds = 0
    total_ms = int(round(seconds * 1000))
    minutes, rest_ms = divmod(total_ms, 60_000)
    secs, ms = divmod(rest_ms, 1000)
    return f"{minutes:02d}:{secs:02d}.{ms:03d}"


def render_vtt(cues: list[Cue]) -> str:
    parts = [
        "WEBVTT",
        "",
        "NOTE",
        "Caption TEXT only. Web overlay (VideoHeroOverlay.tsx) draws the caption",
        "layer itself with brand-styled CSS; positioning/styling lives in CSS,",
        "not in cue settings. One short phrase per cue keeps each caption",
        "to a single line. Generated by tools/export_vtt.py.",
        "",
    ]
    for c in cues:
        parts.append(f"{format_timestamp(c.start)} --> {format_timestamp(c.end)}")
        parts.append(c.text)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def extract_audio_with_ffmpeg(video: Path, audio_out: Path) -> None:
    """Use ffmpeg to extract a 16 kHz mono WAV from the video."""
    if not shutil.which("ffmpeg"):
        sys.exit("error: ffmpeg not found on PATH")
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(video),
            "-ac", "1", "-ar", "16000", "-vn",
            str(audio_out),
        ],
        check=True,
    )


def run_transcribe(audio: Path, screenplay: Path | None, json_out: Path) -> None:
    """Invoke tools/transcribe.py as a subprocess."""
    cmd = [sys.executable, str(TRANSCRIBE_PY), str(audio), "--output", str(json_out)]
    if screenplay and screenplay.is_file():
        cmd.extend(["--screenplay", str(screenplay)])
    subprocess.run(cmd, check=True, cwd=ROOT)


def load_words_from_transcript(json_path: Path) -> list[Word]:
    """Read the transcript JSON and flatten to a list of Word records.

    Compatible with the schema produced by tools/transcribe.py:
    { "segments": [ { "words": [ {"start": ..., "end": ..., "word": ...} ] } ] }
    Falls back to top-level "words" if "segments" missing.
    """
    data = json.loads(json_path.read_text())
    words: list[Word] = []
    if "segments" in data:
        for seg in data["segments"]:
            for w in seg.get("words", []):
                words.append(Word(start=float(w["start"]), end=float(w["end"]), word=str(w["word"]).strip()))
    elif "words" in data:
        for w in data["words"]:
            words.append(Word(start=float(w["start"]), end=float(w["end"]), word=str(w["word"]).strip()))
    else:
        sys.exit("error: transcript JSON has no 'segments' or 'words' field")
    if not words:
        sys.exit("error: transcript produced zero words")
    return words


def main() -> int:
    parser = argparse.ArgumentParser(description="Export WebVTT from a rendered intro video.")
    parser.add_argument("project", help="Project directory name under projects/")
    parser.add_argument("--max-chars", type=int, default=28, help="Max characters per cue (default 28).")
    parser.add_argument("--max-cue-sec", type=float, default=2.0, help="Max seconds per cue (default 2.0).")
    parser.add_argument("--input", help="Override input video path (default: projects/<name>/out/intro.mp4).")
    parser.add_argument("--output", help="Override output VTT path (default: projects/<name>/out/intro.vtt).")
    args = parser.parse_args()

    project_dir = ROOT / "projects" / args.project
    if not project_dir.is_dir():
        sys.exit(f"error: project directory not found: {project_dir}")

    video = Path(args.input) if args.input else project_dir / "out" / "intro.mp4"
    if not video.is_file():
        sys.exit(f"error: video not found: {video}")

    vtt_out = Path(args.output) if args.output else project_dir / "out" / "intro.vtt"
    screenplay = project_dir / "SCREENPLAY.md"

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        audio = tmp_path / "audio.wav"
        transcript_json = tmp_path / "transcript.json"
        print(f"[1/3] Extract audio: {video} → {audio}")
        extract_audio_with_ffmpeg(video, audio)
        print(f"[2/3] Transcribe (Modal Whisper) with screenplay hint: {screenplay if screenplay.is_file() else 'none'}")
        run_transcribe(audio, screenplay if screenplay.is_file() else None, transcript_json)
        print(f"[3/3] Chunk into WebVTT cues (max {args.max_chars} chars, max {args.max_cue_sec}s)")
        words = load_words_from_transcript(transcript_json)
        cues = chunk_words_into_cues(words, max_chars=args.max_chars, max_cue_sec=args.max_cue_sec)
        vtt_out.parent.mkdir(parents=True, exist_ok=True)
        vtt_out.write_text(render_vtt(cues))
        print(f"✔ Wrote {vtt_out} ({len(cues)} cues)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
